# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(416, 277)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 10, 371, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.name_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name_line.setObjectName("name_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_line)
        self.roast_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.roast_line.setObjectName("roast_line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roast_line)
        self.ground_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ground_line.setObjectName("ground_line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ground_line)
        self.price_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.price_line.setObjectName("price_line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.price_line)
        self.volume_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.volume_line.setObjectName("volume_line")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.volume_line)
        self.des_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.des_line.setObjectName("des_line")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.des_line)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 240, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Название"))
        self.label_2.setText(_translate("Form", "Обжарка"))
        self.label_3.setText(_translate("Form", "Молотый / в зернах"))
        self.label_4.setText(_translate("Form", "Цена, руб"))
        self.label_5.setText(_translate("Form", "Объем, г"))
        self.label_6.setText(_translate("Form", "Описание"))
        self.pushButton.setText(_translate("Form", "OK"))
